# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kapsl_inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from ._pool import POOL as _kapsl_descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kapsl_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import open_inference_grpc_pb2 as open__inference__grpc__pb2


DESCRIPTOR = _kapsl_descriptor_pool.AddSerializedFile(b'\n\x15kapsl_inference.proto\x12\x08kapsl.v1\x1a\x19open_inference_grpc.proto\"\x13\n\x11ListModelsRequest\"5\n\x12ListModelsResponse\x12\x1f\n\x06models\x18\x01 \x03(\x0b\x32\x0f.kapsl.v1.Model\"A\n\x05Model\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\r\n\x05ready\x18\x04 \x01(\x08\x32\xa7\x01\n\x0eKapslInference\x12G\n\nListModels\x12\x1b.kapsl.v1.ListModelsRequest\x1a\x1c.kapsl.v1.ListModelsResponse\x12L\n\x0bInferStream\x12\x1c.inference.ModelInferRequest\x1a\x1d.inference.ModelInferResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kapsl_sdk._grpc.kapsl_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTMODELSREQUEST']._serialized_start=62
  _globals['_LISTMODELSREQUEST']._serialized_end=81
  _globals['_LISTMODELSRESPONSE']._serialized_start=83
  _globals['_LISTMODELSRESPONSE']._serialized_end=136
  _globals['_MODEL']._serialized_start=138
  _globals['_MODEL']._serialized_end=203
  _globals['_KAPSLINFERENCE']._serialized_start=206
  _globals['_KAPSLINFERENCE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
