# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kapsl_inference_pb2 as kapsl__inference__pb2
from . import open_inference_grpc_pb2 as open__inference__grpc__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kapsl_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KapslInferenceStub(object):
    """Kapsl extensions to the unary Open Inference Protocol.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModels = channel.unary_unary(
                '/kapsl.v1.KapslInference/ListModels',
                request_serializer=kapsl__inference__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=kapsl__inference__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.unary_stream(
                '/kapsl.v1.KapslInference/InferStream',
                request_serializer=open__inference__grpc__pb2.ModelInferRequest.SerializeToString,
                response_deserializer=open__inference__grpc__pb2.ModelInferResponse.FromString,
                _registered_method=True)


class KapslInferenceServicer(object):
    """Kapsl extensions to the unary Open Inference Protocol.
    """

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request, context):
        """Each response contains one output packet. Successful completion uses OK
        trailers; failure uses a non-OK gRPC status. There is no sentinel packet.
        Cancelling the RPC cancels generation. grpc-timeout covers the whole stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KapslInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=kapsl__inference__pb2.ListModelsRequest.FromString,
                    response_serializer=kapsl__inference__pb2.ListModelsResponse.SerializeToString,
            ),
            'InferStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=open__inference__grpc__pb2.ModelInferRequest.FromString,
                    response_serializer=open__inference__grpc__pb2.ModelInferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kapsl.v1.KapslInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kapsl.v1.KapslInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KapslInference(object):
    """Kapsl extensions to the unary Open Inference Protocol.
    """

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kapsl.v1.KapslInference/ListModels',
            kapsl__inference__pb2.ListModelsRequest.SerializeToString,
            kapsl__inference__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kapsl.v1.KapslInference/InferStream',
            open__inference__grpc__pb2.ModelInferRequest.SerializeToString,
            open__inference__grpc__pb2.ModelInferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
